version: '3.8'

services:
  api:
    build: .
    depends_on:
      - database
      - redis
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    env_file: .env
    environment:
      RAILS_ENV: development
      DATABASE_USER: postgres
      DATABASE_HOST: database
      REDIS_URL: redis://redis:6379/0

  database:
    image: postgres:12.1
    volumes:
      - db_data:/var/lib/postgresql/data

  frontend:
    build: ./app/frontend
    ports:
      - "8080:8080"
    volumes:
      - ./app/frontend:/frontend
      - front_node_modules:/frontend/node_modules

  redis:
      image: 'redis:5'

volumes:
  db_data:
  front_node_modules:
