version: '3.8'

services:
  api:
    build: .
    depends_on:
      - database
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
    env_file: .env
    environment:
      RAILS_ENV: development
      DATABASE_USER: postgres
      DATABASE_HOST: database
      

  database:
    image: postgres:12.1
    volumes:
      - db_data:/var/lib/postgresql/data

  frontend:
    build: ./app/frontend
    ports:
      - "8080:8080"
    volumes:
      - ./app/frontend:/frontend
      - front_node_modules:/frontend/node_modules

volumes:
  gem_cache:
  db_data:
  front_node_modules:
